kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: riak-kv
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: riak-kv
    spec:
      containers:
      - name: riak-kv
        image: stojan/kubriak-kv:latest
