apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: riak-kv
spec:
  replicas: 5
  serviceName: riak-kv
  template:
    metadata:
      labels:
        app: riak-kv
    spec:
      terminationGracePeriodSeconds: 6000
      containers:
        - name: riak-kv
          image: stojan/kubriak-kv:latest
          livenessProbe:
            exec:
              command:
                - "/etc/riak/probes.d/liveness.sh"
          readinessProbe:
            exec:
              command:
                - "/etc/riak/probes.d/readiness.sh"
  volumeClaimTemplates:
    - metadata: 
        name: riak-kv
      spec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
