kind: Service
apiVersion: v1
metadata:
  name: riak-kv
  labels:
    app: riak-kv
spec:
  clusterIP: "None"
  ports:
    - name: protobuf
      port: 8087
      targetPort: 8087
    - name: http
      port: 8098
      targetPort: 8098
  selector:
    app: riak-kv

