#!/bin/bash

CONFIG=/etc/riak/riak.conf
HOSTNAME_IP=`hostname -I | awk '{ print $1; }'`

if [ -z "$RIAK_NODE_NAME" ]
then
  RIAK_NODE_NAME=riak
fi

if [ -z "$RIAK_DISTRIBUTED_COOKIE" ]
then
  RIAK_DISTRIBUTED_COOKIE=riak
fi

echo "# Autogenerated configuration from '/etc/riak/prestart.d/99-autoconfig.sh' via '$0'" >> $CONFIG
echo "nodename = $RIAK_NODE_NAME@$HOSTNAME_IP" >> $CONFIG
echo "distributed_cookie = $RIAK_DISTRIBUTED_COOKIE" >> $CONFIG
echo "listener.protobuf.internal = $HOSTNAME_IP:8087" >> $CONFIG
echo "listener.http.internal = $HOSTNAME_IP:8098" >> $CONFIG

